FROM nvidia/cuda:11.6.1-devel-ubuntu20.04 AS vand_runner

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get install -y \
    curl \
    software-properties-common \
    cmake \
    pkg-config \
    ffmpeg


# Install latest git for github actions
RUN add-apt-repository ppa:git-core/ppa &&\
    apt-get update && \
    apt-get install --no-install-recommends -y git

# Prettier requires atleast nodejs 10 and actions/checkout requires nodejs 16
RUN curl -sL https://deb.nodesource.com/setup_current.x > nodesetup.sh && \
    bash - nodesetup.sh && \
    apt-get install --no-install-recommends -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# the list is cleared on the final stage

# Create a non-root user
RUN useradd -m user
USER user

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
# Ensure the installed binary is on the `PATH`
ENV PATH="/home/user/.local/bin/:$PATH"

# Copy codebase and install dependencies
# This helps in caching the dependencies
COPY --chown=user:user ./eval /home/user/eval
RUN cd /home/user/eval/ && uv sync

# Download gh-actions runner
RUN mkdir -p /home/user/actions-runner
WORKDIR /home/user/actions-runner
RUN curl -o actions-runner-linux-x64-2.322.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-2.322.0.tar.gz && \
    tar xzf ./actions-runner-linux-x64-2.322.0.tar.gz && \
    rm ./actions-runner-linux-x64-2.322.0.tar.gz

WORKDIR /home/user/
